##推荐使用清华大学镜像源
#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

source 'https://github.com/CocoaPods/Specs.git'

##忽略.cocoapods中多个specs源引起的警告问题
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ZHHLoopPagerView_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  # 表示可以使用 swift 的框架
  use_frameworks!
  
  pod 'ZHHLoopPagerView', :path => '../'

  target 'ZHHLoopPagerView_Tests' do
    inherit! :search_paths

    
  end
end
